"""add teams table

Revision ID: 0b57be99ebe5
Revises: 71f3851a386c
Create Date: 2026-08-04 09:22:47.329013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b57be99ebe5'
down_revision: Union[str, Sequence[str], None] = '71f3851a386c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('team_lead_user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.user_id'], name=op.f('fk_teams_created_by_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['department_id'], ['core.departments.department_id'], name=op.f('fk_teams_department_id_departments'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['team_lead_user_id'], ['auth.users.user_id'], name=op.f('fk_teams_team_lead_user_id_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.user_id'], name=op.f('fk_teams_updated_by_users'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk_teams')),
    sa.UniqueConstraint('team_name', name=op.f('uq_teams_team_name')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams', schema='core')
    # ### end Alembic commands ###
