"""modified the table project

Revision ID: 147a2570feac
Revises: 753c447b876e
Create Date: 2026-09-08 17:45:17.917068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147a2570feac'
down_revision: Union[str, Sequence[str], None] = '753c447b876e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'updated_by',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'updated_by',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='core')
    # ### end Alembic commands ###
