"""add configuration tables

Revision ID: 1fd6a786fd15
Revises: 7c1db4383ec8
Create Date: 2026-07-30 15:50:00.879391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd6a786fd15'
down_revision: Union[str, Sequence[str], None] = '7c1db4383ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priorities',
    sa.Column('priority_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority_name', sa.String(length=50), nullable=False),
    sa.Column('priority_code', sa.String(length=50), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('priority_id', name=op.f('pk_priorities')),
    sa.UniqueConstraint('priority_code', name=op.f('uq_priorities_priority_code')),
    sa.UniqueConstraint('priority_level', name=op.f('uq_priorities_priority_level')),
    sa.UniqueConstraint('priority_name', name=op.f('uq_priorities_priority_name')),
    schema='config'
    )
    op.create_table('project_statuses',
    sa.Column('project_status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_closed_status', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('project_status_id', name=op.f('pk_project_statuses')),
    sa.UniqueConstraint('status_code', name=op.f('uq_project_statuses_status_code')),
    sa.UniqueConstraint('status_name', name=op.f('uq_project_statuses_status_name')),
    schema='config'
    )
    op.create_table('task_statuses',
    sa.Column('task_status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_completed_status', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_cancelled_status', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('task_status_id', name=op.f('pk_task_statuses')),
    sa.UniqueConstraint('status_code', name=op.f('uq_task_statuses_status_code')),
    sa.UniqueConstraint('status_name', name=op.f('uq_task_statuses_status_name')),
    schema='config'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_statuses', schema='config')
    op.drop_table('project_statuses', schema='config')
    op.drop_table('priorities', schema='config')
    # ### end Alembic commands ###
