"""add team members table

Revision ID: 2c79b71433f6
Revises: 499f7a5f8bdd
Create Date: 2026-08-11 23:11:23.386213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c79b71433f6'
down_revision: Union[str, Sequence[str], None] = '499f7a5f8bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('team_member_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('member_role', sa.String(length=100), nullable=True),
    sa.Column('capacity_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['auth.users.user_id'], name=op.f('fk_team_members_added_by_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['team_id'], ['core.teams.team_id'], name=op.f('fk_team_members_team_id_teams'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_team_members_user_id_users'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('team_member_id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_team_id_user_id'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members', schema='core')
    # ### end Alembic commands ###
