"""add departments table

Revision ID: 4b305c2ac458
Revises: bfb23c4ab895
Create Date: 2026-07-31 11:44:57.549866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b305c2ac458'
down_revision: Union[str, Sequence[str], None] = 'bfb23c4ab895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('manager_user_id', sa.BigInteger(), nullable=True),
    sa.Column('supervisor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['auth.users.user_id'], name=op.f('fk_departments_manager_user_id_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['auth.users.user_id'], name=op.f('fk_departments_supervisor_user_id_users'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('department_id', name=op.f('pk_departments')),
    sa.UniqueConstraint('department_name', name=op.f('uq_departments_department_name')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments', schema='core')
    # ### end Alembic commands ###
