"""add work_item_types table

Revision ID: 4f739bbf14d0
Revises: 147a2570feac
Create Date: 2026-09-21 22:06:24.734320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f739bbf14d0'
down_revision: Union[str, Sequence[str], None] = '147a2570feac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_item_types',
    sa.Column('work_item_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('code_prefix', sa.String(length=10), nullable=False),
    sa.Column('requires_project', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('icon_name', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('work_item_type_id', name=op.f('pk_work_item_types')),
    sa.UniqueConstraint('code_prefix', name=op.f('uq_work_item_types_code_prefix')),
    sa.UniqueConstraint('type_name', name=op.f('uq_work_item_types_type_name')),
    schema='config'
    )
    op.create_index(op.f('ix_config_work_item_types_type_code'), 'work_item_types', ['type_code'], unique=True, schema='config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_work_item_types_type_code'), table_name='work_item_types', schema='config')
    op.drop_table('work_item_types', schema='config')
    # ### end Alembic commands ###
