"""modify users table make department_id nullable

Revision ID: 71f3851a386c
Revises: 4b305c2ac458
Create Date: 2026-07-31 11:47:43.942864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f3851a386c'
down_revision: Union[str, Sequence[str], None] = '4b305c2ac458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_users_department_id_departments', 'users', 'departments', ['department_id'], ['department_id'], source_schema='auth', referent_schema='core', ondelete='NO ACTION', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_department_id_departments', 'users', schema='auth', type_='foreignkey')
    # ### end Alembic commands ###
