"""modify the user agent column and fix the user relationship

Revision ID: 7c1db4383ec8
Revises: d2c7a61c5f56
Create Date: 2026-07-22 21:46:22.750190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1db4383ec8'
down_revision: Union[str, Sequence[str], None] = 'd2c7a61c5f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_sessions', sa.Column('user_agent', sa.String(length=1000), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_sessions', 'user_agent', schema='auth')
    # ### end Alembic commands ###
