"""make updated by nullable True in team tbl

Revision ID: a05eb44b8bc8
Revises: 0b57be99ebe5
Create Date: 2026-08-08 18:29:58.102845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05eb44b8bc8'
down_revision: Union[str, Sequence[str], None] = '0b57be99ebe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'updated_by',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'updated_by',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='core')
    # ### end Alembic commands ###
