"""add tasks table

Revision ID: cf01da93a6e8
Revises: e5dac0c3fe42
Create Date: 2026-09-25 15:44:00.361418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf01da93a6e8'
down_revision: Union[str, Sequence[str], None] = 'e5dac0c3fe42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_code', sa.String(length=50), nullable=False),
    sa.Column('work_item_type_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_task_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_status_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimaed_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.user_id'], name=op.f('fk_tasks_created_by_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['core.tasks.task_id'], name=op.f('fk_tasks_parent_task_id_tasks'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['priority_id'], ['config.priorities.priority_id'], name=op.f('fk_tasks_priority_id_priorities'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.project_id'], name=op.f('fk_tasks_project_id_projects'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['auth.users.user_id'], name=op.f('fk_tasks_reporter_user_id_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['task_status_id'], ['config.task_statuses.task_status_id'], name=op.f('fk_tasks_task_status_id_task_statuses'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.user_id'], name=op.f('fk_tasks_updated_by_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['work_item_type_id'], ['config.work_item_types.work_item_type_id'], name=op.f('fk_tasks_work_item_type_id_work_item_types'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('task_code', name=op.f('uq_tasks_task_code')),
    schema='core'
    )
    op.create_index(op.f('ix_core_tasks_priority_id'), 'tasks', ['priority_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tasks_project_id'), 'tasks', ['project_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tasks_task_status_id'), 'tasks', ['task_status_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_tasks_work_item_type_id'), 'tasks', ['work_item_type_id'], unique=False, schema='core')
    op.create_index('ix_tasks_project_priority', 'tasks', ['project_id', 'priority_id'], unique=False, schema='core')
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'task_status_id'], unique=False, schema='core')
    op.create_index('ix_tasks_type_status', 'tasks', ['work_item_type_id', 'task_status_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_type_status', table_name='tasks', schema='core')
    op.drop_index('ix_tasks_project_status', table_name='tasks', schema='core')
    op.drop_index('ix_tasks_project_priority', table_name='tasks', schema='core')
    op.drop_index(op.f('ix_core_tasks_work_item_type_id'), table_name='tasks', schema='core')
    op.drop_index(op.f('ix_core_tasks_task_status_id'), table_name='tasks', schema='core')
    op.drop_index(op.f('ix_core_tasks_project_id'), table_name='tasks', schema='core')
    op.drop_index(op.f('ix_core_tasks_priority_id'), table_name='tasks', schema='core')
    op.drop_table('tasks', schema='core')
    # ### end Alembic commands ###
