"""add refresh sessions model

Revision ID: d2c7a61c5f56
Revises: d98871ee5a60
Create Date: 2026-07-21 10:11:36.782262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'd2c7a61c5f56'
down_revision: Union[str, Sequence[str], None] = 'd98871ee5a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_sessions',
    sa.Column('refresh_session_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_family_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('token_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_token_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], name=op.f('fk_refresh_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('refresh_session_id', name=op.f('pk_refresh_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_sessions_token_hash')),
    sa.UniqueConstraint('token_id', name=op.f('uq_refresh_sessions_token_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_refresh_sessions_session_family_id'), 'refresh_sessions', ['session_family_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_refresh_sessions_user_id_revoked_at', 'refresh_sessions', ['user_id', 'revoked_at'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_sessions_user_id_revoked_at', table_name='refresh_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_sessions_user_id'), table_name='refresh_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_sessions_session_family_id'), table_name='refresh_sessions', schema='auth')
    op.drop_table('refresh_sessions', schema='auth')
    # ### end Alembic commands ###
