"""add projects table

Revision ID: d6db06a2ab54
Revises: 2c79b71433f6
Create Date: 2026-08-27 22:20:00.585691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6db06a2ab54'
down_revision: Union[str, Sequence[str], None] = '2c79b71433f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_status_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('target_end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.user_id'], name=op.f('fk_projects_created_by_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth.users.user_id'], name=op.f('fk_projects_owner_user_id_users'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['priority_id'], ['config.priorities.priority_id'], name=op.f('fk_projects_priority_id_priorities')),
    sa.ForeignKeyConstraint(['project_status_id'], ['config.project_statuses.project_status_id'], name=op.f('fk_projects_project_status_id_project_statuses')),
    sa.ForeignKeyConstraint(['team_id'], ['core.teams.team_id'], name=op.f('fk_projects_team_id_teams'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.user_id'], name=op.f('fk_projects_updated_by_users'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects')),
    sa.UniqueConstraint('project_code', name=op.f('uq_projects_project_code')),
    schema='core'
    )
    op.create_index('ix_projects_priority_id_owner_user_id_team_id_target_end_date', 'projects', ['priority_id', 'owner_user_id', 'team_id', 'target_end_date'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_priority_id_owner_user_id_team_id_target_end_date', table_name='projects', schema='core')
    op.drop_table('projects', schema='core')
    # ### end Alembic commands ###
