"""remove requires_project column on work items types tbl

Revision ID: e5dac0c3fe42
Revises: 4f739bbf14d0
Create Date: 2026-09-24 21:28:03.511161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'e5dac0c3fe42'
down_revision: Union[str, Sequence[str], None] = '4f739bbf14d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_item_types', 'requires_project', schema='config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_item_types', sa.Column('requires_project', mssql.BIT(), server_default=sa.text("('0')"), autoincrement=False, nullable=False), schema='config')
    # ### end Alembic commands ###
